##############################################################################
# Grafana Auto-Provisioning: InfluxDB Data Source
# This file auto-configures the InfluxDB connection on first start
##############################################################################

apiVersion: 1

datasources:
  - name: InfluxDB-WEG
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    jsonData:
      version: Flux
      organization: tecnoelectric
      defaultBucket: weg_drives
      tlsSkipVerify: true
    secureJsonData:
      token: u54oZUhFSS1ECuUvCtOYhxaEJ18mPPwqp8cZPZqkbrvs1NQ47OwH99SupjPWpkromjQOnL2nBAaaf8St9dkt1g==
    editable: true
