var fs = require('fs');
var f = JSON.parse(fs.readFileSync('/data/flows.json', 'utf8'));
var cfg = f.find(function(n) { return n.id === 'weg_d2_config_form'; });

var T = [];
T.push('<template>');
T.push('<div style="width:100%;padding:16px;font-family:Arial,sans-serif">');
T.push('  <div style="display:flex;align-items:center;justify-content:space-between;margin-bottom:16px">');
T.push('    <h2 style="color:#1a4d8f;margin:0">Configuracion de Dispositivos</h2>');
T.push('    <button @click="showAdd=true" style="background:#1a4d8f;color:white;border:none;padding:10px 20px;border-radius:6px;cursor:pointer;font-weight:bold">+ Agregar Drive</button>');
T.push('  </div>');
T.push('  <div v-if="info" style="padding:10px;border-radius:6px;margin-bottom:12px;font-weight:bold" :style="{background:infoOk?\'#e8f5e9\':\'#fbe9e7\',color:infoOk?\'#2e7d32\':\'#c62828\'}">{{info}}</div>');
T.push('  <div v-if="!loaded" style="text-align:center;padding:40px;color:#999">Cargando...</div>');
T.push('  <div v-if="loaded">');
// Gateways
T.push('    <h3 style="color:#333;margin:0 0 8px">Gateways</h3>');
T.push('    <table style="width:100%;border-collapse:collapse;margin-bottom:24px">');
T.push('      <tr style="background:#1a4d8f;color:white"><th style="padding:10px;text-align:left">Nombre</th><th style="padding:10px;text-align:left">IP</th><th style="padding:10px">Puerto</th><th style="padding:10px;text-align:left">Sitio</th></tr>');
T.push('      <tr v-for="g in gateways" :key="g.name" style="border-bottom:1px solid #e0e0e0">');
T.push('        <td style="padding:10px;font-weight:bold">{{g.name}}</td>');
T.push('        <td style="padding:10px;font-family:monospace">{{g.ip}}</td>');
T.push('        <td style="padding:10px;text-align:center">{{g.port}}</td>');
T.push('        <td style="padding:10px">{{g.site}}</td>');
T.push('      </tr>');
T.push('    </table>');
// Devices table
T.push('    <h3 style="color:#333;margin:0 0 8px">Dispositivos ({{devices.length}})</h3>');
T.push('    <table style="width:100%;border-collapse:collapse">');
T.push('      <tr style="background:#1a4d8f;color:white"><th style="padding:8px;text-align:left">Nombre</th><th style="padding:8px">Tipo</th><th style="padding:8px;text-align:left">Sitio</th><th style="padding:8px;text-align:left">IP</th><th style="padding:8px">Puerto</th><th style="padding:8px">Unit ID</th><th style="padding:8px">Acciones</th></tr>');
T.push('      <tr v-for="(d,i) in devices" :key="d.name+i" style="border-bottom:1px solid #e0e0e0">');
// Edit mode
T.push('        <template v-if="editIdx===i">');
T.push('          <td style="padding:6px"><input v-model="editDev.name" style="width:100%;padding:6px;border:1px solid #ccc;border-radius:4px" /></td>');
T.push('          <td style="padding:6px"><select v-model="editDev.type" style="padding:6px;border:1px solid #ccc;border-radius:4px"><option>CFW900</option><option>SSW900</option></select></td>');
T.push('          <td style="padding:6px"><select v-model="editDev.site" style="padding:6px;border:1px solid #ccc;border-radius:4px"><option>Agriplus</option><option>Agrocaraya</option></select></td>');
T.push('          <td style="padding:6px"><input v-model="editDev.ip" style="width:100%;padding:6px;border:1px solid #ccc;border-radius:4px;font-family:monospace" /></td>');
T.push('          <td style="padding:6px"><input v-model.number="editDev.port" type="number" style="width:70px;padding:6px;border:1px solid #ccc;border-radius:4px;text-align:center" /></td>');
T.push('          <td style="padding:6px"><input v-model.number="editDev.unitId" type="number" style="width:50px;padding:6px;border:1px solid #ccc;border-radius:4px;text-align:center" /></td>');
T.push('          <td style="padding:6px;white-space:nowrap"><button @click="saveEdit(i)" style="background:#2e7d32;color:white;border:none;padding:5px 12px;border-radius:4px;cursor:pointer;margin-right:4px">Guardar</button><button @click="editIdx=-1" style="background:#999;color:white;border:none;padding:5px 12px;border-radius:4px;cursor:pointer">Cancelar</button></td>');
T.push('        </template>');
// View mode
T.push('        <template v-else>');
T.push('          <td style="padding:8px;font-weight:bold">{{d.name}}</td>');
T.push('          <td style="padding:8px;text-align:center"><span :style="{background:d.type===\'CFW900\'?\'#e3f2fd\':\'#f3e5f5\',color:d.type===\'CFW900\'?\'#1565c0\':\'#7b1fa2\',padding:\'2px 10px\',borderRadius:\'12px\',fontSize:\'12px\',fontWeight:\'bold\'}">{{d.type}}</span></td>');
T.push('          <td style="padding:8px">{{d.site}}</td>');
T.push('          <td style="padding:8px;font-family:monospace">{{d.ip}}</td>');
T.push('          <td style="padding:8px;text-align:center">{{d.port}}</td>');
T.push('          <td style="padding:8px;text-align:center">{{d.unitId}}</td>');
T.push('          <td style="padding:8px;white-space:nowrap"><button @click="startEdit(i)" style="background:#1a4d8f;color:white;border:none;padding:5px 12px;border-radius:4px;cursor:pointer;margin-right:4px">Editar</button><button @click="delDevice(d.name)" style="background:#c62828;color:white;border:none;padding:5px 12px;border-radius:4px;cursor:pointer">Eliminar</button></td>');
T.push('        </template>');
T.push('      </tr>');
T.push('    </table>');
T.push('  </div>');
// Add modal
T.push('  <div v-if="showAdd" style="position:fixed;top:0;left:0;width:100%;height:100%;background:rgba(0,0,0,0.5);display:flex;align-items:center;justify-content:center;z-index:999">');
T.push('    <div style="background:white;padding:24px;border-radius:12px;width:420px;max-width:90%">');
T.push('      <h3 style="color:#1a4d8f;margin:0 0 16px">Agregar Dispositivo</h3>');
T.push('      <div style="display:flex;flex-direction:column;gap:10px">');
T.push('        <div><label style="font-size:12px;color:#666;font-weight:bold;display:block;margin-bottom:2px">Nombre</label><input v-model="newDev.name" placeholder="SAER X" style="width:100%;padding:8px;border:1px solid #ccc;border-radius:4px;box-sizing:border-box" /></div>');
T.push('        <div><label style="font-size:12px;color:#666;font-weight:bold;display:block;margin-bottom:2px">Tipo</label><select v-model="newDev.type" style="width:100%;padding:8px;border:1px solid #ccc;border-radius:4px"><option>CFW900</option><option>SSW900</option></select></div>');
T.push('        <div><label style="font-size:12px;color:#666;font-weight:bold;display:block;margin-bottom:2px">Sitio</label><select v-model="newDev.site" style="width:100%;padding:8px;border:1px solid #ccc;border-radius:4px"><option>Agriplus</option><option>Agrocaraya</option></select></div>');
T.push('        <div><label style="font-size:12px;color:#666;font-weight:bold;display:block;margin-bottom:2px">IP</label><input v-model="newDev.ip" placeholder="192.168.10.x" style="width:100%;padding:8px;border:1px solid #ccc;border-radius:4px;font-family:monospace;box-sizing:border-box" /></div>');
T.push('        <div style="display:flex;gap:10px">');
T.push('          <div style="flex:1"><label style="font-size:12px;color:#666;font-weight:bold;display:block;margin-bottom:2px">Puerto</label><input v-model.number="newDev.port" type="number" style="width:100%;padding:8px;border:1px solid #ccc;border-radius:4px;box-sizing:border-box" /></div>');
T.push('          <div style="flex:1"><label style="font-size:12px;color:#666;font-weight:bold;display:block;margin-bottom:2px">Unit ID</label><input v-model.number="newDev.unitId" type="number" style="width:100%;padding:8px;border:1px solid #ccc;border-radius:4px;box-sizing:border-box" /></div>');
T.push('        </div>');
T.push('      </div>');
T.push('      <div style="display:flex;gap:10px;margin-top:16px;justify-content:flex-end">');
T.push('        <button @click="showAdd=false" style="background:#999;color:white;border:none;padding:10px 20px;border-radius:6px;cursor:pointer">Cancelar</button>');
T.push('        <button @click="addDevice" style="background:#1a4d8f;color:white;border:none;padding:10px 20px;border-radius:6px;cursor:pointer;font-weight:bold">Agregar</button>');
T.push('      </div>');
T.push('    </div>');
T.push('  </div>');
T.push('</div>');
T.push('</template>');
// Script
T.push('<script>');
T.push('export default {');
T.push('  data: function() {');
T.push('    return {');
T.push('      devices:[], gateways:[], loaded:false, info:"", infoOk:true,');
T.push('      showAdd:false, editIdx:-1,');
T.push('      newDev:{name:"",type:"CFW900",site:"Agriplus",ip:"",port:502,unitId:1},');
T.push('      editDev:{}');
T.push('    }');
T.push('  },');
T.push('  mounted: function() { this.load(); },');
T.push('  methods: {');
T.push('    api: function() { return "http://"+window.location.hostname+":3200"; },');
T.push('    load: function() {');
T.push('      var self=this;');
T.push('      Promise.all([');
T.push('        fetch(self.api()+"/api/config/devices").then(function(r){return r.json()}),');
T.push('        fetch(self.api()+"/api/config/gateways").then(function(r){return r.json()})');
T.push('      ]).then(function(res){ self.devices=res[0]; self.gateways=res[1]; self.loaded=true; })');
T.push('        .catch(function(e){ self.info="Error: "+e.message; self.infoOk=false; self.loaded=true; });');
T.push('    },');
T.push('    addDevice: function() {');
T.push('      var self=this;');
T.push('      fetch(self.api()+"/api/config/devices",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(self.newDev)})');
T.push('        .then(function(r){ if(!r.ok) return r.json().then(function(e){throw new Error(e.error)}); return r.json(); })');
T.push('        .then(function(){ self.showAdd=false; self.newDev={name:"",type:"CFW900",site:"Agriplus",ip:"",port:502,unitId:1}; self.info="Dispositivo agregado"; self.infoOk=true; self.load(); setTimeout(function(){self.info=""},3000); })');
T.push('        .catch(function(e){ self.info="Error: "+e.message; self.infoOk=false; });');
T.push('    },');
T.push('    startEdit: function(i) { this.editIdx=i; this.editDev=JSON.parse(JSON.stringify(this.devices[i])); },');
T.push('    saveEdit: function(i) {');
T.push('      var self=this;');
T.push('      self.devices[i]=JSON.parse(JSON.stringify(self.editDev));');
T.push('      fetch(self.api()+"/api/config/devices",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(self.devices)})');
T.push('        .then(function(r){return r.json()})');
T.push('        .then(function(){ self.editIdx=-1; self.info="Dispositivo actualizado"; self.infoOk=true; setTimeout(function(){self.info=""},3000); })');
T.push('        .catch(function(e){ self.info="Error: "+e.message; self.infoOk=false; });');
T.push('    },');
T.push('    delDevice: function(name) {');
T.push('      if(!confirm("Eliminar "+name+"?")) return;');
T.push('      var self=this;');
T.push('      fetch(self.api()+"/api/config/devices/"+encodeURIComponent(name),{method:"DELETE"})');
T.push('        .then(function(r){return r.json()})');
T.push('        .then(function(){ self.info=name+" eliminado"; self.infoOk=true; self.load(); setTimeout(function(){self.info=""},3000); })');
T.push('        .catch(function(e){ self.info="Error: "+e.message; self.infoOk=false; });');
T.push('    }');
T.push('  }');
T.push('}');
T.push('<' + '/script>');

cfg.format = T.join('\n');
fs.writeFileSync('/data/flows.json', JSON.stringify(f, null, 2));
console.log('Config page updated: ' + cfg.format.length + ' chars');
