var fs = require('fs');
var f = JSON.parse(fs.readFileSync('/data/flows.json', 'utf8'));
var rpt = f.find(function(n) { return n.id === 'weg_d2_report_form'; });

var T = [];
T.push('<template>');
T.push('<div style="width:100%;padding:16px;font-family:Arial,sans-serif">');
T.push('  <h2 style="color:#1a4d8f;margin:0 0 16px">Generador de Reportes</h2>');
// Filters bar
T.push('  <div style="padding:16px;background:#f5f5f5;border-radius:8px;margin-bottom:16px">');
T.push('    <div style="display:flex;gap:16px;flex-wrap:wrap;align-items:flex-start">');
// Time range
T.push('      <div>');
T.push('        <label style="font-size:12px;color:#666;font-weight:bold;display:block;margin-bottom:4px">Rango de Tiempo</label>');
T.push('        <select v-model="fromRange" style="padding:10px;border:1px solid #ccc;border-radius:4px;font-size:14px;min-width:180px">');
T.push('          <option value="-1h">Ultima hora</option>');
T.push('          <option value="-6h">Ultimas 6 horas</option>');
T.push('          <option value="-24h">Ultimas 24 horas</option>');
T.push('          <option value="-7d">Ultima semana</option>');
T.push('          <option value="-30d">Ultimo mes</option>');
T.push('        </select>');
T.push('      </div>');
// Site filter
T.push('      <div>');
T.push('        <label style="font-size:12px;color:#666;font-weight:bold;display:block;margin-bottom:4px">Sitio</label>');
T.push('        <div style="display:flex;gap:6px;flex-wrap:wrap">');
T.push('          <button v-for="s in allSites" :key="s" @click="toggleSite(s)" :style="{padding:\'8px 14px\',border:\'1px solid\',borderColor:selSites.includes(s)?\'#1a4d8f\':\'#ccc\',borderRadius:\'4px\',cursor:\'pointer\',fontWeight:\'bold\',fontSize:\'13px\',background:selSites.includes(s)?\'#1a4d8f\':\'white\',color:selSites.includes(s)?\'white\':\'#333\'}">{{s}}</button>');
T.push('        </div>');
T.push('      </div>');
// Device filter
T.push('      <div>');
T.push('        <label style="font-size:12px;color:#666;font-weight:bold;display:block;margin-bottom:4px">Dispositivos</label>');
T.push('        <div style="display:flex;gap:6px;flex-wrap:wrap">');
T.push('          <label v-for="d in filteredDevices" :key="d" style="display:flex;align-items:center;gap:4px;padding:6px 10px;border:1px solid #ccc;border-radius:4px;cursor:pointer;font-size:13px" :style="{borderColor:selDevices.includes(d)?\'#1a4d8f\':\'#ccc\',background:selDevices.includes(d)?\'#e3f2fd\':\'white\'}">');
T.push('            <input type="checkbox" :value="d" v-model="selDevices" style="margin:0" /> {{d}}');
T.push('          </label>');
T.push('        </div>');
T.push('      </div>');
T.push('    </div>');
// Action buttons
T.push('    <div style="display:flex;gap:10px;margin-top:16px">');
T.push('      <button @click="preview" :disabled="loading" style="background:#1a4d8f;color:white;border:none;padding:10px 24px;border-radius:6px;cursor:pointer;font-weight:bold;font-size:14px">');
T.push('        {{ loading ? "Consultando..." : "Vista Previa" }}');
T.push('      </button>');
T.push('      <button @click="dl(\'csv\')" :disabled="loading || !rows.length" style="background:#2e7d32;color:white;border:none;padding:10px 24px;border-radius:6px;cursor:pointer;font-weight:bold;font-size:14px">');
T.push('        Descargar CSV');
T.push('      </button>');
T.push('      <button @click="dl(\'pdf\')" :disabled="loading || !rows.length" style="background:#c62828;color:white;border:none;padding:10px 24px;border-radius:6px;cursor:pointer;font-weight:bold;font-size:14px">');
T.push('        Descargar PDF');
T.push('      </button>');
T.push('    </div>');
T.push('  </div>');
// Status
T.push('  <div v-if="info" style="padding:10px;border-radius:6px;margin-bottom:12px;font-weight:bold" :style="{background:infoOk?\'#e8f5e9\':\'#fbe9e7\',color:infoOk?\'#2e7d32\':\'#c62828\'}">{{info}}</div>');
// Summary cards
T.push('  <div v-if="rows.length" style="display:flex;gap:12px;margin-bottom:16px;flex-wrap:wrap">');
T.push('    <div style="background:white;border:1px solid #e0e0e0;border-radius:8px;padding:12px 20px"><div style="font-size:12px;color:#666">Registros</div><div style="font-size:24px;font-weight:bold;color:#1a4d8f">{{rows.length}}</div></div>');
T.push('    <div style="background:white;border:1px solid #e0e0e0;border-radius:8px;padding:12px 20px"><div style="font-size:12px;color:#666">Drives</div><div style="font-size:24px;font-weight:bold;color:#1a4d8f">{{uniqueDrives}}</div></div>');
T.push('    <div style="background:white;border:1px solid #e0e0e0;border-radius:8px;padding:12px 20px"><div style="font-size:12px;color:#666">Rango</div><div style="font-size:14px;font-weight:bold;color:#333">{{rangeLabel}}</div></div>');
T.push('  </div>');
// Table
T.push('  <div v-if="rows.length" style="overflow-x:auto;max-height:500px;overflow-y:auto;border:1px solid #e0e0e0;border-radius:8px">');
T.push('    <table style="width:100%;border-collapse:collapse;font-size:13px">');
T.push('      <tr style="background:#1a4d8f;color:white;position:sticky;top:0;z-index:1">');
T.push('        <th v-for="h in displayHeaders" :key="h.key" style="padding:10px;text-align:left;white-space:nowrap">{{h.label}}</th>');
T.push('      </tr>');
T.push('      <tr v-for="(row,i) in rows.slice(0,300)" :key="i" :style="{background:i%2===0?\'#fafafa\':\'#fff\'}">');
T.push('        <td v-for="h in displayHeaders" :key="h.key" style="padding:8px 10px;border-bottom:1px solid #eee;white-space:nowrap">{{formatVal(row[h.key],h.key)}}</td>');
T.push('      </tr>');
T.push('    </table>');
T.push('  </div>');
T.push('  <p v-if="rows.length>300" style="color:#999;font-size:12px;margin-top:8px">Mostrando 300 de {{rows.length}}. Descargue CSV/PDF para todos.</p>');
T.push('  <div v-if="!rows.length && !loading && queried" style="text-align:center;padding:60px;color:#999"><p style="font-size:18px">Sin datos para el rango seleccionado</p></div>');
T.push('</div>');
T.push('</template>');
// Script
T.push('<script>');
T.push('export default {');
T.push('  data: function() {');
T.push('    return {');
T.push('      fromRange:"-24h", loading:false, info:"", infoOk:true, rows:[], headers:[], queried:false,');
T.push('      allDevices:[], allSites:[], selDevices:[], selSites:[], deviceData:[],');
T.push('      rangeLabels:{"-1h":"Ultima hora","-6h":"6 horas","-24h":"24 horas","-7d":"7 dias","-30d":"30 dias"}');
T.push('    }');
T.push('  },');
T.push('  computed: {');
T.push('    uniqueDrives: function() { var n={}; this.rows.forEach(function(r){if(r.name)n[r.name]=1}); return Object.keys(n).length; },');
T.push('    rangeLabel: function() { return this.rangeLabels[this.fromRange]||this.fromRange; },');
T.push('    filteredDevices: function() { var s=this.selSites; var dd=this.deviceData; return dd.filter(function(d){return s.includes(d.site)}).map(function(d){return d.name}); },');
T.push('    displayHeaders: function() {');
T.push('      var map={"_time":"Fecha/Hora","name":"Drive","site":"Sitio","current":"Corriente (A)","voltage":"Voltaje (V)","power":"Potencia (kW)","motor_temp":"Temp Motor (C)","frequency":"Frecuencia (Hz)","motor_speed":"Velocidad (RPM)"};');
T.push('      var order=["_time","name","site","current","voltage","power","frequency","motor_speed","motor_temp"];');
T.push('      var h=this.headers;');
T.push('      return order.filter(function(k){return h.indexOf(k)>=0}).map(function(k){return{key:k,label:map[k]||k}});');
T.push('    }');
T.push('  },');
T.push('  watch: {');
T.push('    selSites: function() {');
T.push('      var fd=this.filteredDevices; var self=this;');
T.push('      self.selDevices=self.selDevices.filter(function(d){return fd.includes(d)});');
T.push('      if(!self.selDevices.length) self.selDevices=fd.slice();');
T.push('    }');
T.push('  },');
T.push('  mounted: function() {');
T.push('    var self=this;');
T.push('    fetch("http://"+window.location.hostname+":3200/api/config/devices").then(function(r){return r.json()}).then(function(devs){');
T.push('      self.deviceData=devs;');
T.push('      self.allDevices=devs.map(function(d){return d.name});');
T.push('      var sites={}; devs.forEach(function(d){sites[d.site]=1}); self.allSites=Object.keys(sites);');
T.push('      self.selSites=self.allSites.slice();');
T.push('      self.selDevices=self.allDevices.slice();');
T.push('    }).catch(function(){});');
T.push('  },');
T.push('  methods: {');
T.push('    api: function(){return "http://"+window.location.hostname+":3200"},');
T.push('    toggleSite: function(s) { var i=this.selSites.indexOf(s); if(i>=0)this.selSites.splice(i,1); else this.selSites.push(s); },');
T.push('    formatVal: function(v,key) {');
T.push('      if(!v&&v!==0) return "-";');
T.push('      if(key==="_time"){var d=new Date(v);return d.toLocaleDateString("es-PY")+" "+d.toLocaleTimeString("es-PY")}');
T.push('      if(typeof v==="number") return parseFloat(v.toFixed(2));');
T.push('      var n=parseFloat(v); if(!isNaN(n)&&v.toString().includes(".")) return parseFloat(n.toFixed(2));');
T.push('      return v;');
T.push('    },');
T.push('    preview: function() {');
T.push('      this.loading=true;this.info="";this.queried=false;var self=this;');
T.push('      var body={from:this.fromRange};');
T.push('      if(self.selDevices.length<self.allDevices.length) body.devices=self.selDevices;');
T.push('      fetch(self.api()+"/api/reports/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)})');
T.push('        .then(function(r){return r.json()}).then(function(d){');
T.push('          self.rows=d.data||[];self.headers=self.rows.length?Object.keys(self.rows[0]):[];');
T.push('          self.loading=false;self.queried=true;');
T.push('          if(self.rows.length){self.info=self.rows.length+" registros";self.infoOk=true}');
T.push('          setTimeout(function(){self.info=""},4000);');
T.push('        }).catch(function(e){self.loading=false;self.info="Error: "+e.message;self.infoOk=false;self.queried=true});');
T.push('    },');
T.push('    dl: function(type) {');
T.push('      this.loading=true;var self=this;');
T.push('      var body={from:this.fromRange,title:"Reporte WEG SCADA"};');
T.push('      if(self.selDevices.length<self.allDevices.length) body.devices=self.selDevices;');
T.push('      fetch(self.api()+"/api/reports/"+type,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)})');
T.push('        .then(function(r){return r.blob()}).then(function(b){');
T.push('          var a=document.createElement("a");a.href=URL.createObjectURL(b);a.download="weg-report."+type;a.click();');
T.push('          self.loading=false;self.info=type.toUpperCase()+" descargado";self.infoOk=true;setTimeout(function(){self.info=""},3000);');
T.push('        }).catch(function(e){self.loading=false;self.info="Error: "+e.message;self.infoOk=false});');
T.push('    }');
T.push('  }');
T.push('}');
T.push('<' + '/script>');

rpt.format = T.join('\n');
fs.writeFileSync('/data/flows.json', JSON.stringify(f, null, 2));
console.log('Report page updated: ' + rpt.format.length + ' chars');
