'use strict';

// Códigos de protección/falla (F) y alarma (A) del CFW900, con el nombre corto
// de la Tabla 2.1 del manual de programación (WEG 10008985503).
const CFW900_CODES = {
  A018: 'Tensión Baja de la Batería',
  A019: 'Sobretensión de la Fuente 24 Vcc',
  A020: 'Subtensión de la Fuente',
  F021: 'Subtensión Link DC',
  F022: 'Sobretensión Link DC',
  F025: 'Falla Señales PWM',
  F030: 'IGBT U Desat.',
  F034: 'IGBT V Desat.',
  F038: 'IGBT W Desat.',
  F042: 'IGBT Frenado Desat.',
  A046: 'Carga Alta en el Motor',
  A047: 'Carga Alta en los IGBTs',
  F048: 'Sobrecarga en los IGBTs',
  A050: 'Sobretemp. IGBT1 U',
  A051: 'Sobretemp. IGBT1 V',
  A052: 'Sobretemp. IGBT1 W',
  F053: 'Sobretemp. IGBT1 U',
  F054: 'Sobretemp. IGBT1 V',
  F055: 'Sobretemp. IGBT1 W',
  A060: 'Sobretemp. Junción IGBT/DRL',
  F061: 'Sobretemp. Junción IGBT/DRL',
  F067: 'Cableado Invertido Encoder/Motor',
  F069: 'Sobrecorr. Baja Frec. Salida',
  F070: 'Cortocirc. Link DC',
  F071: 'Sobrecorr. en la Salida',
  F072: 'Sobrecarga en el Motor',
  F073: 'Sobrecorriente por Software',
  F074: 'Falla a Tierra',
  F076: 'Corriente Deseq. Motor',
  F077: 'Sobrecarga Res. Fren.',
  F078: 'Sobretemper. Motor',
  F084: 'Falla de Autodiagnóstico',
  A090: 'Alarma Externa',
  F091: 'Protección Externa',
  F099: 'Offset Cor. Inválido',
  F104: 'Falla en el Convertidor A/D',
  A110: 'Temperatura Motor Alta',
  A128: 'Timeout Comunicación Serial',
  A129: 'Módulo Anybus Offline',
  A130: 'Error de acceso al Módulo Anybus',
  A133: 'Sin Alimentación en la Interfaz CAN',
  A134: 'Bus Off',
  A135: 'CANopen Offline',
  A136: 'Maestro en Idle',
  A137: 'Timeout en la conexión DeviceNet',
  A145: 'Timeout Conexión SNTP',
  A147: 'Comunicación EtherNet/IP Offline',
  A149: 'Timeout Modbus TCP',
  F150: 'Sobreveloc. Motor',
  A152: 'Sobretemp. Circ. Pot.',
  F153: 'Sobretemp. Circ. Pot.',
  A154: 'Sobretemp. Circ. Cont.',
  F155: 'Sobretemp. Circ. Cont.',
  A156: 'Subtemperatura en el convertidor',
  F157: 'Subtemperatura en el convertidor',
  F158: 'Configuración Corrompida',
  F160: 'Falla de la STO90',
  F161: 'STO90 Offline',
  A164: 'Limitación Link DC',
  F165: 'Limitación Link DC',
  A166: 'Limitación de Corriente',
  F167: 'Limitación de Corriente',
  A168: 'Limitación de Torque',
  F169: 'Limitación de Torque',
  F171: 'Veloc. Vent. Pot. 1',
  F172: 'Veloc. Vent. Pot. 2',
  F173: 'Veloc. Vent. Pot. 3',
  F174: 'Veloc. Vent. Pot. 4',
  F175: 'Veloc. Vent. Int. 1',
  F176: 'Veloc. Vent. Int. 2',
  A177: 'Sustitución Ventilador',
  F185: 'Protección de Precarga',
  A186: 'Veloc. Vent. Pot. 1',
  A187: 'Veloc. Vent. Pot. 2',
  A188: 'Veloc. Vent. Pot. 3',
  A189: 'Veloc. Vent. Pot. 4',
  A190: 'Veloc. Vent. Int. 1',
  A191: 'Veloc. Vent. Int. 2',
  F228: 'Timeout Comunicación Serial',
  F229: 'Módulo Anybus Offline',
  F230: 'Error de acceso al Módulo Anybus',
  F233: 'Sin Alimentación en la Interfaz CAN',
  F234: 'Bus Off',
  F235: 'CANopen Offline',
  F236: 'Maestro en Idle',
  F237: 'Timeout en la Conexión DeviceNet',
  F247: 'Comunicación EtherNet/IP Offline',
  F249: 'Timeout Modbus TCP',
  A430: 'Nivel bajo de la PV del PID',
  F431: 'Nivel bajo de la PV del PID',
  A432: 'Nivel Alto de la PV del PID',
  F433: 'Nivel Alto de la PV del PID',
  F600: 'Falla en la Actualización de Pulsos',
  F605: 'Circuito de Potencia Apagado',
  F606: 'Power Monitor Comm Lost',
  F607: 'SMM Comm Lost'
};

// "A" + 110 → "A110 Temperatura Motor Alta". Código desconocido → solo el código.
function codeLabel(prefix, n) {
  const code = prefix + String(n).padStart(3, '0');
  const name = CFW900_CODES[code];
  return name ? `${code} ${name}` : code;
}

// Lista de posiciones (0 = vacía) → texto unido con " / ".
function codesText(prefix, values) {
  return values.filter(v => v > 0).map(v => codeLabel(prefix, v)).join(' / ');
}

module.exports = { CFW900_CODES, codeLabel, codesText };
