var fs = require('fs');
var f = JSON.parse(fs.readFileSync('/data/flows.json', 'utf8'));
var ui = f.find(function(n) { return n.id === 'weg_alarm_sp_ui'; });

var tmpl = [
'<template>',
'<div style="padding:12px;width:100%">',
'  <div style="display:flex;align-items:center;justify-content:space-between;margin-bottom:16px;flex-wrap:wrap;gap:8px">',
'    <div>',
'      <h2 style="margin:0;color:#1a4d8f">Setpoints de Alarma por Drive</h2>',
'      <p style="margin:4px 0 0;color:#666;font-size:13px">Cada drive tiene sus propios limites</p>',
'    </div>',
'    <button @click="doSave" :disabled="saving" style="background:#1a4d8f;color:white;border:none;padding:10px 24px;border-radius:6px;font-size:14px;cursor:pointer;font-weight:bold">',
'      {{ saving ? "Guardando..." : "Guardar Setpoints" }}',
'    </button>',
'  </div>',
'  <div v-if="info" style="padding:10px;border-radius:6px;margin-bottom:12px;background:#e8f5e9;color:#2e7d32;font-weight:bold">{{ info }}</div>',
'  <div v-if="!loaded" style="text-align:center;padding:40px;color:#999">Cargando...</div>',
'  <div v-for="d in drives" :key="d.name" style="background:white;border:1px solid #e0e0e0;border-radius:8px;padding:16px;margin-bottom:12px;width:100%">',
'    <div style="display:flex;align-items:center;gap:10px;margin-bottom:12px;flex-wrap:wrap">',
'      <strong style="font-size:16px;color:#1a4d8f">{{ d.name }}</strong>',
'      <span style="background:#e3f2fd;color:#1565c0;padding:2px 10px;border-radius:12px;font-size:12px;font-weight:bold">{{ d.type }}</span>',
'      <span style="background:#f3e5f5;color:#7b1fa2;padding:2px 10px;border-radius:12px;font-size:12px">{{ d.site }}</span>',
'    </div>',
'    <div style="display:grid;grid-template-columns:repeat(4,1fr);gap:10px">',
'      <div style="padding:8px;border-radius:6px;background:#fafafa">',
'        <label style="font-size:11px;color:#666;font-weight:bold;display:block;margin-bottom:4px">Corriente Alta (A)</label>',
'        <input type="number" step="1" min="0" v-model.number="d.sp.currentHigh" style="width:100%;padding:8px;border:1px solid #ccc;border-radius:4px;font-size:15px;font-weight:bold;text-align:center" />',
'      </div>',
'      <div style="padding:8px;border-radius:6px;background:#fafafa">',
'        <label style="font-size:11px;color:#666;font-weight:bold;display:block;margin-bottom:4px">Temp. Alta (C)</label>',
'        <input type="number" step="1" min="0" v-model.number="d.sp.tempHigh" style="width:100%;padding:8px;border:1px solid #ccc;border-radius:4px;font-size:15px;font-weight:bold;text-align:center" />',
'      </div>',
'      <div style="padding:8px;border-radius:6px;background:#fafafa">',
'        <label style="font-size:11px;color:#666;font-weight:bold;display:block;margin-bottom:4px">Frec. Alta (Hz)</label>',
'        <input type="number" step="1" min="0" v-model.number="d.sp.frequencyHigh" style="width:100%;padding:8px;border:1px solid #ccc;border-radius:4px;font-size:15px;font-weight:bold;text-align:center" />',
'      </div>',
'      <div style="padding:8px;border-radius:6px;background:#fafafa">',
'        <label style="font-size:11px;color:#666;font-weight:bold;display:block;margin-bottom:4px">Err. Comm Max</label>',
'        <input type="number" step="1" min="0" v-model.number="d.sp.commErrorMax" style="width:100%;padding:8px;border:1px solid #ccc;border-radius:4px;font-size:15px;font-weight:bold;text-align:center" />',
'      </div>',
'    </div>',
'    <div style="margin-top:10px;display:flex;gap:8px">',
'      <button @click="copyType(d)" style="background:none;border:1px solid #1a4d8f;color:#1a4d8f;padding:5px 14px;border-radius:4px;font-size:12px;cursor:pointer">Copiar a todos los {{ d.type }}</button>',
'      <button @click="resetOne(d)" style="background:none;border:1px solid #999;color:#666;padding:5px 14px;border-radius:4px;font-size:12px;cursor:pointer">Restaurar defaults</button>',
'    </div>',
'  </div>',
'</div>',
'</template>',
'<script>',
'export default {',
'  data: function() {',
'    return { drives: [], defs: {}, loaded: false, saving: false, info: "" }',
'  },',
'  watch: {',
'    msg: {',
'      handler: function(val) {',
'        if (!val || !val.topic) return;',
'        if (val.topic === "spLoad") {',
'          this.defs = val.payload.defaults || {};',
'          var devs = val.payload.devices || [];',
'          var ovr = val.payload.overrides || {};',
'          var self = this;',
'          this.drives = devs.map(function(d) {',
'            var td = self.defs[d.type] || {};',
'            var ov = ovr[d.name] || {};',
'            return { name: d.name, type: d.type, site: d.site, sp: Object.assign({}, td, ov) };',
'          });',
'          this.loaded = true;',
'        }',
'        if (val.topic === "spSaved") {',
'          this.saving = false;',
'          this.info = "Setpoints guardados";',
'          var self = this;',
'          setTimeout(function() { self.info = ""; }, 3000);',
'        }',
'      },',
'      deep: true',
'    }',
'  },',
'  methods: {',
'    doSave: function() {',
'      this.saving = true;',
'      var ovr = {};',
'      var self = this;',
'      this.drives.forEach(function(d) {',
'        var td = self.defs[d.type] || {};',
'        var diff = {};',
'        var has = false;',
'        Object.keys(d.sp).forEach(function(k) {',
'          if (d.sp[k] !== td[k]) { diff[k] = d.sp[k]; has = true; }',
'        });',
'        if (has) ovr[d.name] = diff;',
'      });',
'      this.send({ topic: "spSave", payload: { defaults: self.defs, overrides: ovr } });',
'    },',
'    copyType: function(src) {',
'      var self = this;',
'      this.drives.forEach(function(d) {',
'        if (d.type === src.type && d.name !== src.name) d.sp = Object.assign({}, src.sp);',
'      });',
'      this.info = "Copiado a todos los " + src.type;',
'      setTimeout(function() { self.info = ""; }, 2000);',
'    },',
'    resetOne: function(d) {',
'      d.sp = Object.assign({}, this.defs[d.type] || {});',
'    }',
'  }',
'}',
'<' + '/script>'
].join('\n');

ui.format = tmpl;
fs.writeFileSync('/data/flows.json', JSON.stringify(f, null, 2));
console.log('Template set: ' + tmpl.length + ' chars');
