apiVersion: 1

contactPoints:
  - orgId: 1
    name: WEG SCADA Notifications
    receivers:
      - uid: weg-email-contact
        type: email
        settings:
          addresses: "scada@tecnoelectric.local"
          singleEmail: true
        disableResolveMessage: false
